update posting an event to MMS
metno/data-management-handbook pull request #105
Opened 2023-11-02 14:34 UTC by shamlymajeed

2023-11-02 17:09 UTC, mortenwh requested changes
Thanks! I have a few suggestions. Also, please write how the user can get an api-key, and explain  TotalCount, event-interval and NextEventAt.

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +`ntotal` is the `TotalCount` and `event-interval` is used to make
Can you explain TotalCount, event-interval and NextEventAt? What do they mean?

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +Make sure you have one valid api-key to publish an event to MMS.
How can the user get this?

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +  ./mms post --api-key=validKey --production-hub=https://mms-api.s-enda-*.k8s.met.no --queue-name=queueName --jobname=test --product=test --product-location=test-location --production-hub=https://mms
```suggestion
  ./mms post --api-key=validKey --production-hub=https://mms-api.s-enda.k8s.met.no --queue-name=queueName --jobname=test --product=test --product-location=test-location --production-hub=https://mms-api.s-enda-*.k8s.met.no --MMD="$(cat /path/to/MMdfile.xml)" --counter=1 --ntotal=1 --reftime=2023-11-02T12:02:46Z --event-interval=3
```

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> + ./mms subscribe --production-hub=nats://nats.s-enda-*.k8s.met.no:32001 --queue-name=queueName --cred-file=path/to/credFile.creds --queue-name=queueName --nats-local=false
```suggestion
 ./mms subscribe --production-hub=nats://nats.s-enda.k8s.met.no:32001 --queue-name=queueName --cred-file=path/to/credFile.creds --queue-name=queueName --nats-local=false
```

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +
Or let's just use the production environment, since dev and staging is for ourselves..

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +Make sure you have one valid cred file to subscribe to a queue .
```suggestion
Make sure you have a valid cred file to subscribe to a queue .
```

2023-11-02 17:09 UTC, mortenwh commented on source/register_context.adoc
> +`MMD-Agent` is subscribing to all these messages coming through the event queue. If the messsage contains a MMD payload, it will post the MMD file to `DMCI`.
```suggestion
The `MMD-Agent` is subscribed to all the messages coming through the event queue. If the messsage contains a MMD payload, it will post the MMD file to the DMCI API, which stores the metadata in the catalog.
```

2023-11-03 08:59 UTC, shamlymajeed commented on source/register_context.adoc
> +Make sure you have one valid api-key to publish an event to MMS.
We have to decide on how we should provide the cred file to the user or should they generate the cred files.
Because we have to shell into the nats-box container and have to generate it there.

2023-11-03 11:25 UTC, mortenwh commented on source/register_context.adoc
> +Make sure you have one valid api-key to publish an event to MMS.
Ok - so it means someone needs to help the user, right? Is that you or Espen? We have a "service organisation" in the data management organisation system: https://docs.google.com/document/d/1tmgYaAwsJ3sl0UpkdtKsHGc48fgD6tvplUGvMaerSDc/edit#heading=h.3mzq4wv - I can see if we have a group email for that, then we could add you and Espen?

2023-11-03 11:27 UTC, mortenwh commented on source/register_context.adoc
> +`ntotal` is the `TotalCount` and `event-interval` is used to make
yes, that would be great!

2023-11-03 11:30 UTC, mortenwh commented on source/register_context.adoc
> +
I'll commit the current suggestion. Sorry for the confusion - it's hard to agree with myself... Anyway, we can try like this, and see how it works

2023-11-03 11:31 UTC, mortenwh commented on source/register_context.adoc
> +The `MMD-Agent` is subscribed to all the messages coming through the event queue. If the messsage contains a MMD payload, it will post the MMD file to the DMCI API, which stores the metadata in the c
```suggestion
The `MMD-Agent` subscribes to all the messages coming through the event queue. If the message contains an MMD payload, it will post the MMD file to the DMCI API, which stores the metadata in the catalog.
```

2023-11-03 11:33 UTC, mortenwh commented on source/register_context.adoc
> +where UUID should be replaced by your dataset uuid (not `no.met:UUID`). Others ways to check are:
```suggestion
where UUID should be replaced by your dataset uuid (not `no.met:UUID` but only the `UUID`). Others ways to check are:
```

2023-11-03 11:33 UTC, mortenwh commented on source/register_context.adoc
> +* Find the datasets having a given `metadata_identifier = no.met:4a34334b-b384-48b3-b846-76807bc006`: `https://csw.s-enda*.k8s.met.no/csw?service=CSW&version=2.0.2&request=GetRecordById&oxml&outputSc
```suggestion
* Find the dataset having a given `metadata_identifier = no.met:4a34334b-b384-48b3-b846-76807bc006`: `https://csw.s-enda*.k8s.met.no/csw?service=CSW&version=2.0.2&request=GetRecordById&oxml&outputSchema=http://www.isotc211.org/2005/gmd&elementsetname=full&id=no.met:4a34334b-b384-48b3-b846-76807bc006`
```

2023-11-03 11:35 UTC, shamlymajeed commented on source/register_context.adoc
> +Make sure you have one valid api-key to publish an event to MMS.
Yes . I think you can add both of us.

2023-11-03 12:01 UTC, mortenwh commented on source/register_context.adoc
> +Make sure you have one valid api-key to publish an event to MMS.
```suggestion
Make sure you have a valid API-key to publish an event to MMS. You can get the key by contacting the mailto:dm-service-organisation@met.no[Service Organisation] for data management.
```

2023-11-03 12:03 UTC, mortenwh commented on source/register_context.adoc
> +
```suggestion
```

2023-11-03 12:04 UTC, mortenwh commented on source/register_context.adoc
> +`NextEventAt` in Product Event.
```suggestion
`NextEventAt` in link:https://github.com/metno/MMS/blob/main/messages.md[Product Event].
```

2023-11-03 12:05 UTC, mortenwh commented on source/register_context.adoc
> +`ntotal` is the `TotalCount` and `event-interval` is used to make
```suggestion
Note that `ntotal` is the `TotalCount` and `event-interval` is used to make 
```

2023-11-03 12:07 UTC, mortenwh commented on source/register_context.adoc
> +----
```suggestion
```

2023-11-03 12:07 UTC, mortenwh commented on source/register_context.adoc
> +Push the Product Event to MMS:
```suggestion
Push the Product Event to MMS:

[source]
----
  ./mms post --api-key=validKey --production-hub=https://mms-api.s-enda.k8s.met.no --queue-name=queueName --jobname=test --product=test --product-location=test-location --production-hub=https://mms-api.s-enda-*.k8s.met.no --MMD="$(cat /path/to/MMdfile.xml)" --counter=1 --ntotal=1 --reftime=2023-11-02T12:02:46Z --event-interval=3
----
```

2023-11-03 12:09 UTC, mortenwh commented on source/register_context.adoc
> +  Include the arguments required to make the link:https://github.com/metno/MMS/blob/main/messages.md[Product Event]
```suggestion
 The arguments required  for the Product Event are explained link:https://github.com/metno/MMS/blob/main/messages.md[here].
```

2023-11-03 12:09 UTC, mortenwh commented on source/register_context.adoc
> +  in the post command.
```suggestion
```

2023-11-03 12:10 UTC, mortenwh commented on source/register_context.adoc
> +Alternatively, use the staging environment for testing; https://mms-api.s-enda-staging.k8s.met.no
```suggestion
Alternatively, use the staging environment for testing; `https://mms-api.s-enda-staging.k8s.met.no`.
```

2023-11-03 12:10 UTC, mortenwh commented on source/register_context.adoc
> +Note that `ntotal` is the `TotalCount` and `event-interval` is used to make
```suggestion
Note that `ntotal` is the `TotalCount`, and that `event-interval` is used to make 
```

2023-11-03 12:11 UTC, mortenwh commented on source/register_context.adoc
> +`NextEventAt` in link:https://github.com/metno/MMS/blob/main/messages.md[Product Event].
```suggestion
`NextEventAt` (see link:https://github.com/metno/MMS/blob/main/messages.md[Product Event]).
```

2023-11-03 12:15 UTC, mortenwh commented on source/register_context.adoc
> +
```suggestion
Make sure you also have a valid credential file to **subscribe** to a queue .

```

2023-11-03 12:17 UTC, mortenwh approved these changes

2023-11-03 12:20 UTC, mortenwh commented on source/register_context.adoc
> +`NextEventAt` in link:https://github.com/metno/MMS/blob/main/messages.md[Product Event].
```suggestion
`NextEventAt` (see link:https://github.com/metno/MMS/blob/main/messages.md[Product Event]).
```

2023-11-03 12:21 UTC, merged