#36 Update path to csw endpoint
metno/data-management-handbook pull request #37
Opened 2021-05-10 08:24 UTC by ElodieFZ

Update path to csw endpoint in search examples.

2021-05-12 08:13 UTC, mortenwh requested changes
Looks good - but I have a few comments. I also just realised that it would be really good with an example for a geographical search. Also, maybe we should just use the development server for examples here... Also in section 6.3.1

2021-05-12 08:13 UTC, mortenwh commented on doc/search_context.adoc
>  ==== Online catalog
I think this could be subsection of section "6.3.1 User searches the catalog with OpenSearch". Can that section also be renamed to "OpenSearch"? The point should be demonstrate the most common search queries. As such, we should perhaps also add an example of a geographical search, as the users are probably most interested in searching in time and space.

The virtual machines are now being changed as well but we can update the text for that when we're done with (or as part of) https://app.zenhub.com/workspaces/s-enda-5e7b1b4acfc5ca185fb6b53c/issues/metno/s-enda-project-plan/428

2021-05-12 08:13 UTC, mortenwh commented on doc/search_context.adoc
> +A staging server for the CSW catalog service is available at link:https://csw-staging.s-enda.k8s.met.no. This can be used from QGIS, as follows:
let's use the production server in this example

2021-05-12 08:13 UTC, mortenwh commented on doc/search_context.adoc
> +. Type `https://csw-staging.s-enda.k8s.met.no` for the URL
production server

2021-05-12 14:09 UTC, ElodieFZ commented on doc/search_context.adoc
> +A staging server for the CSW catalog service is available at link:https://csw-staging.s-enda.k8s.met.no. This can be used from QGIS, as follows:
I agree that in the end it should be the production server. But is it already up? I used this `https://gitlab.met.no/tjenester/s-enda` as a reference and it says that the production endpoint is not available yet.

2021-05-12 17:44 UTC, mortenwh commented on doc/search_context.adoc
> +A staging server for the CSW catalog service is available at link:https://csw-staging.s-enda.k8s.met.no. This can be used from QGIS, as follows:
No, it's not up yet. I was thinking that we could just write this as if it is up, though. Then we don't need to change it later :)

2021-05-18 11:39 UTC, ElodieFZ commented on doc/search_context.adoc
>  ==== Online catalog
I have re-organized a bit the OpenSearch section to try and make it more clear. What do you think?

2021-05-19 09:02 UTC, mortenwh requested changes
Thanks - very nice with the geographic search example. I suggest to change the base url of the examples to the productions server..

2021-05-19 09:55 UTC, mortenwh commented
One more thing - do you know if it possible to do searches for intersecting polygons? Is it enough to extend the bbox? Or do we need to use plain CSW for that? Could you check a bit? That kind of search will provide much more accurate results than a simple corner based search.

2021-05-19 13:21 UTC, ElodieFZ commented on doc/search_context.adoc
>  ====
Yes, I just tested it, the dates work as expected now. I'll remove the note.

2021-05-20 14:13 UTC, ElodieFZ commented
I checked a while and asked to Massimo too. It's not straighforward to search with geometries, inclusion, exclusion etc . So I think it's beyond the scope of the simple pycsw exemples of this document.

2021-05-21 07:21 UTC, mortenwh commented
Ok. Actually, I don't agree that it is beyond scope. This (plus temporal search) is the most important search method, and what the users will be looking for first. If it is not possible with opensearch - can we add documentation for how to do it with csw in python? I think this should be prioritized..

2021-05-21 07:26 UTC, mortenwh requested changes
I still think we should add another spatial search example.

2021-05-21 07:26 UTC, mortenwh commented on doc/search_context.adoc
>  This will return a description document of the catalog service. The `URL` field in the description document is a template format that can be used to represent a parameterized form of the search. The
This part should be updated when @aheimsbakk is done with the new vagrant. Maybe today. It could be done in this PR, otherwise let's make a new issue :)

2021-05-26 11:31 UTC, mortenwh commented on doc/search_context.adoc
>  This will return a description document of the catalog service. The `URL` field in the description document is a template format that can be used to represent a parameterized form of the search. The
we'll do this in another issue

2021-05-26 11:39 UTC, mortenwh approved these changes
Very nice - thanks! I have a few minor suggestions for language edits. When this is done, the PR can be merged :)

2021-05-26 11:39 UTC, mortenwh commented on doc/search_context.adoc
> +Pycsw only supports geographical searches querying for a box. For more advanced geographical searches, one must write his own XML files. For example:
```suggestion
PyCSW opensearch only supports geographical searches querying for a box. For more advanced geographical searches, one must write specific XML files. For example:
```

2021-05-26 11:39 UTC, mortenwh commented on doc/search_context.adoc
> +* to find all datasets that contains a point
```suggestion
* To find all datasets containing a point:
```

2021-05-26 11:39 UTC, mortenwh commented on doc/search_context.adoc
> +* to find all datasets that intersects a polygon
```suggestion
* To find all datasets intersecting a polygon:
```

2021-05-26 11:39 UTC, mortenwh commented on doc/search_context.adoc
> +* How to use the XML file to query the CSW endpoint with python:
```suggestion
* Then, you can query the CSW endpoint with, e.g., python:
```

2021-05-26 11:39 UTC, mortenwh commented on doc/search_context.adoc
> +The production server for the CSW catalog service is available at `https://csw.s-enda.k8s.met.no`. This can be used from QGIS as follows:
```suggestion
MET Norway's S-ENDA CSW catalog service is available at `https://csw.s-enda.k8s.met.no`. This can be used from QGIS as follows:
```

2021-05-26 11:51 UTC, merged