#44 update paths to images
metno/data-management-handbook pull request #45
Opened 2021-05-19 13:01 UTC by ElodieFZ

Update paths for images in doc files.
Extra option in pdf creation to specify the images path.
Extra option in html creation to copy images in html folder.

2021-05-20 14:58 UTC, ElodieFZ commented
I have actually found a better compiling html that allows to embed the images directly in the html.

2021-05-20 15:03 UTC, ElodieFZ commented on doc/human-roles.adoc
> +image::information-to-knowledge.png[Information-to-knowledge]
I have commented that part as it seems not used?
The png image appears well as is. It is not referenced as a figure though. Should I add that (figure and legend, like for the other png in the doc)?

2021-05-20 15:03 UTC, ElodieFZ commented on doc/human-roles.adoc
> -  (Consume data) as (CD0)
same here

2021-05-21 08:15 UTC, mortenwh commented on doc/human-roles.adoc
> +image::information-to-knowledge.png[Information-to-knowledge]
No, it is used. The compiler creates the png files based on the code. I don't think the png's should be in version control.

2021-05-21 08:15 UTC, mortenwh commented on doc/human-roles.adoc
> -  (Consume data) as (CD0)
this is also used

2021-05-21 08:24 UTC, mortenwh requested changes
the uml diagram codes should be taken back. The figures came up fine in the master branch as well as in the local versions compiled in the vm. Apart from that, it looks good except we should remove the met logo in this general version :)

2021-05-21 08:24 UTC, mortenwh commented on doc/human-roles.adoc
> +//....
this part should be restored. The code is used to create the uml diagrams. The resulting png files should not be in version control.

2021-05-21 08:24 UTC, mortenwh commented on doc/human-roles.adoc
> +//....
this should also be restored

2021-05-21 08:24 UTC, mortenwh commented on doc/data-management-handbook.adoc
> +:title-logo-image: image::Met_RGB_Horisontal_Engelsk.png[pdfwidth=10cm,align=right]
I don't see this one in the compiled html. But I guess it shouldn't be here anyway, since this is the general DMH template? I suggest to remove this line and the file (the file should be added to our gitlab repo instead).
```suggestion
```

2021-05-21 08:49 UTC, ElodieFZ commented on doc/human-roles.adoc
> +//....
yes. 
Two things though. The comment in the code says the diagram does not work. Is it obsolete and should be removed or what is it refering to?
The png files are currently in master part of the version control. You agree they should be removed, both in the html and in the pdf directories? While I'm at it, do you agree that also the resulting pdf and html documents should not be in version control?

2021-05-21 08:53 UTC, mortenwh commented on doc/human-roles.adoc
> +//....
- ah - I must have forgotten to remove the comment...
- yes, let's try to take them out - they are generated every time we compile
- yes, if it still works... I think we need to do something in github then, but these files cause a lot of conflicts, so it's probably better to not have them under vc

2021-05-21 09:00 UTC, ElodieFZ commented on doc/human-roles.adoc
> +//....
Yes. That's why I want to remove them, it's a pain each time one tries to do sthg with github as they change each time. I have seen that you did that in the gitlab version (remove the pdf html from vc) and it seems to work fine.

2021-05-21 09:01 UTC, mortenwh commented on doc/human-roles.adoc
> +//....
yes - can you try?

2021-05-21 09:02 UTC, mortenwh commented on doc/human-roles.adoc
> +//....
maybe a new issue, or just in this PR? Do as you find best :)

2021-05-21 09:19 UTC, ElodieFZ commented on doc/human-roles.adoc
> +//....
I was gonna do it in a new issue to keep things clear as much as possible :-)

2021-05-21 13:55 UTC, mortenwh approved these changes
I removed a few comments. Also, the file from py-mmd-tools has been updated. It will be removed from vc in a nother branch.

2021-05-21 13:55 UTC, merged