Issue3 introduction general
metno/data-management-handbook pull request #8
Opened 2021-02-19 12:01 UTC by niellaNina

Ready for review, is this general enough

2021-02-23 09:49 UTC, ElodieFZ requested changes
Nice work! I seems to me it's easier to read now, there are less big chunks of text. I review from the pdf, so I made comments on both the text and how it looks like in the final pdf.

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +This DMH focuses on the management of geophysical data, types of data and the usage of these data are described in the organisation specific information in Section X.X.X.
I think something is odd with this sentence. Maybe split it in two?

```suggestion
This DMH focuses on the management of geophysical data. Types of data and the usage of these data are described in the organisation specific information in Section X.X.X.
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +2. Read Chapters 2-5 to learn about how data management is currently implemented and how it is expected to evolve in the next few years:
```suggestion
2. Read Chapters 2-5 to learn about how data management is currently implemented and how it is expected to evolve in the next few years;
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +3. Go to the Quick Manual for Data Providers for guidelines on what to do in real-life cases; alternatively Chapter 6 for typical workflow examples.
```suggestion
3. Read the Quick Manual for Data Providers for guidelines on what to do in real-life cases; alternatively read Chapter 6 for typical workflow examples.
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +*the ease of building specific metadata catalogues and data portals that include data from MET Norway and can target a specific user community;
```suggestion
* the ease of building specific metadata catalogues and data portals that include data from MET Norway and can target a specific user community;
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +*the ease of building specific metadata catalogues and data portals that include data from MET Norway and can target a specific user community;
```suggestion
*the ease of building specific metadata catalogues and data portals that include data from the institute and can target a specific user community;
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +The documentation identifies who, what, when, where, and how and shall make it easy for consumers to find and understand data. This requires application of information containers and utilisation of c
```suggestion
The documentation identifies who, what, when, where, and how, and shall make it easy for consumers to find and understand data. This requires application of information containers and utilisation of controlled vocabularies and ontologies where textual representation is required. It also covers the topic of data provenance which is used to describe the origin and all actions done on a dataset. Data provenance is closely linked with workflow management. Furthermore, it covers the relationship between datasets. Application of ontologies in data documentation is closely linked to the concept of linked data. 
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +|Used to tune portal services for datasets for users.
```suggestion
|Used to tune portal services for datasets for users
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +|System metadata covers e.g. technical details of the storage system (e.g. Lustre metadata), web services their purpose and how they interact with other components of the data management system, avai
```suggestion
|System metadata covers e.g. technical details of the storage system (e.g. Lustre metadata), web services, their purpose and how they interact with other components of the data management system, available and consumed storage, number of users and other KPI elements etc.
```

2021-02-23 09:49 UTC, ElodieFZ commented on doc/introduction.adoc
> +|[[site-metadata]]Site metadata
I would put site metadata just after use metadata as they are kind of related. Then put the configuration metadata and system metadata.

2021-02-24 08:12 UTC, niellaNina commented on doc/glossary.adoc
> +|A dataset that “may be a NetCDF, HDF5, GRIB, etc. file, an OPeNDAP dataset, a collection of files, or anything else which can be accessed through the NetCDF API.” https://www.unidata.ucar.edu/softwa
Added this to the list of things to check in the next issue

2021-02-24 08:12 UTC, niellaNina commented on doc/glossary.adoc
> +
I will look into this

2021-02-24 08:16 UTC, niellaNina commented on doc/introduction.adoc
> +|[[site-metadata]]Site metadata
I will move this in the next issue

2021-02-24 08:18 UTC, merged

2021-02-24 08:19 UTC, niellaNina commented
The more deep changes will be moved to a new issue