start work on example script to add all the needed metadata
metno/data-management-handbook pull request #80
Opened 2022-11-14 08:36 UTC by charlienegri

closes #76

2022-11-14 09:28 UTC, mortenwh requested changes

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +
```suggestion
# filename.py

```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +
f.history += 'isotime, Dummy User, filename.py\n' # history should already exist in the netcdf file

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    coverstart = datetime(1900, 1, 1, 0, 0)  + timedelta(44012)
```suggestion
    coverstart = datetime(1900, 1, 1, 0, 0)  + timedelta(44012)  # time of first measurement
```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    coverend = coverstart
```suggestion
    coverend = coverstart  # time of last measurement
```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    # only 1 timestep in this example
```suggestion
    # only 1 timestep (e.g., one measurement) in this example
```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.ancillary_timeliness = '[???]'
```suggestion
```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.Conventions = 'CF-1.6 for coordinates,ACDD-1.3'
```suggestion
    f.Conventions = 'CF-1.6, ACDD-1.3'
```

2022-11-14 09:28 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +The below is an example python script to add to a netCDF the metadata needed for it to be parsed by https://github.com/metno/py-mmd-tools/blob/master/py_mmd_tools/nc_to_mmd.py:
```suggestion
The below is an example python script to add metadata to a netCDF-CF file. Note that we have only included the required attributes, and that the data producer should add more. This is needed for the netCDF file to be parsed into an MMD xml file by the script `scripts/nc2mmd.py` in https://github.com/metno/py-mmd-tools[py-mmd-tools]:
```

2022-11-18 11:59 UTC, mortenwh requested changes
I made a few edits to make it easier to read. As we do in the other repo's line lengths should be max 97 characters, and line lengths in comments should be max 70 characters.

Apart from that, this still needs some work, in particular to make sure that users cannot be mislead. Can you work with this, then I take another review at next iteration?

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +        print("warning: no history field in the netCDF metadata")
strictly speaking, I would use the standard warning package instead..

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.collection = '[e.g. METNCS]'
This is better to leave out. It is not in the attributes list either, is it?
```suggestion
```

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.keywords += 'GCMDLOC:Geographic Region > Northern Hemisphere, '
Why did you add this? I am curious, since it will be useful to know where the confusion is coming from. In principle, the keywords should be descriptive of the data inside the dataset.
```suggestion
```

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +                )
same for this
```suggestion
```

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.keywords = 'GCMDSK:Earth Science > Atmosphere > Atmospheric radiation, '
Maybe we should describe the example dataset a bit before the script or in a comment here so people don't just copy it and use it for

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +                )
```suggestion
```

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +                    'nasjonal-temainndeling'
`keywords_resource` is not in the attributes list either..
```suggestion
```

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    coverstart = datetime(1900, 1, 1, 0, 0)  + timedelta(44012)
we should set the timezone here as well, since the "Z" below refers to utc... And maybe print as isoformat to avoid hardcoding. What if the time that a user has is not really in utc? Then an ignorant user will introduce an error.

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.time_coverage_start = '{:%Y-%m-%dT%H:%M:%S.%f}Z'.format(coverstart)
use another function to print the time variable directly in isoformat

2022-11-18 11:59 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    if 'created_date' in f.ncattrs() and 'created_hour' in f.ncattrs():
`created_date` and `created_hour` are not standard attributes. You should rather assume that you have a time variable, and use the first and the last time in that. This assumption should also be pointed out.

2022-11-18 13:43 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +    f.keywords += 'GCMDLOC:Geographic Region > Northern Hemisphere, '
is this not consistent with the geographic span of the data?  
since we have 
```
    f.geospatial_lat_min = 30.05
    f.geospatial_lat_max = 81.95
    f.geospatial_lon_min = -29.95
    f.geospatial_lon_max = 89.95
```
but maybe I misunderstand the field

2023-01-19 14:06 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.keywords += 'GCMDLOC:Geographic Region > Northern Hemisphere, '
I see. I don't think the geographic location is needed here, although it is not necessarily a problem. The important ones are GCMDSK, GEMET and NORTHEMES. I'll commit the change suggestion above.

2023-01-19 14:09 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.keywords = 'GCMDSK:Earth Science > Atmosphere > Atmospheric radiation, '
yes - we need to say which variables that are supposed to be in the example dataset, and connect the keywords to them. This should include explicit comments in the code.

2023-02-01 16:13 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.keywords = 'GCMDSK:Earth Science > Atmosphere > Atmospheric radiation, '
This is now wind speed and direction, as mentioned above. Can you update the keywords?

2023-02-01 16:14 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    try:
Simplify code:
```suggestion
```

2023-02-01 16:14 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +        warnings.warn("Warning: conversion of first timestep to datetime in ISO format failed, setting time_coverage_start as ")
```suggestion
```

2023-02-01 16:15 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +        f.time_coverage_start = datetime.fromtimestamp(coverstart).replace(tzinfo=timezone.utc).isoformat()
```suggestion
    f.time_coverage_start = datetime.fromtimestamp(coverstart).replace(tzinfo=timezone.utc).isoformat()
```

2023-02-01 16:15 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    try:
```suggestion
```

2023-02-01 16:15 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +        warnings.warn("Conversion of last timestep to datetime in ISO format failed, time_coverage_end will not be set")
```suggestion
```

2023-02-01 16:16 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +            f.date_created = isotime_now_utc
should be simplified since it is just an example

2023-02-01 16:16 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.Conventions = 'CF-1.6, ACDD-1.3'
Check what's the latest versions...

2023-02-01 16:18 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    f.iso_topic_category = 'climatologyMeteorologyAtmosphere,environment'
See https://apps.usgs.gov/thesaurus/thesaurus-full.php?thcode=15 - I don't think "environment" is correct here. At least, climatologyMeteorologyAtmosphere is good enough.
```suggestion
    f.iso_topic_category = 'climatologyMeteorologyAtmosphere'
```

2023-02-02 10:41 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +            f.date_created = isotime_now_utc
as in just setting the created date as today if not 'date_created' in f.ncattrs()?

or keeping `if 'created_date' in f.ncattrs():` and :  
 - assuming that if it's there then it's what's needed already (no check of 'created_hour') 
 - setting the created date as today if not there
 
 or something else?

2023-02-02 10:42 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +    try:
am not sure I understand here, you want to eliminate the check?

2023-02-02 11:31 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +    try:
yes, we should assume it's working since we just need to show the principles

2023-02-02 11:40 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +            f.date_created = isotime_now_utc
My understanding is that you assume here that the file already exists. But does that mean that it has been created by CDO? If that's the case, it should be described before the script example. Also, if CDO adds the created_date by default then you don't need to do anything. If CDO doesn't create the attribute, then we need to add it in the example.

Another use case is if you create the nc-file from scratch. Then this needs to be explained. But I guess the CDO use case is relevant for many people at MET, so we can use that - but it needs to be clear by the introduction text before the script. The script code should be as simple as possible in order to make it easily readable, so avoid `try-except`s, `if`s, and warnings.

2023-02-02 12:42 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +            f.date_created = isotime_now_utc
I wasn't assuming anything specific about the creation of the file,   
created_date is not part of any standard `cdo` output afaik  
the code was inspired by created_date and created_hour as they are in the emep model run files   
I have simplified the code now

2023-02-03 14:18 UTC, charlienegri commented
@mortenwh tried to do as we discussed, my colleague Magnus helped with the thredds file since he's in the thredds users list already, take a look and let me know what you think

2023-02-03 21:26 UTC, mortenwh commented
It was very good to have the netcdf file! I had a look and made some updates. I had to change the way you read the times, and also added some more attributes. Now it's your turn to review, I guess :)

2023-02-06 08:44 UTC, charlienegri commented
looks fine :+1:

2023-02-07 13:15 UTC, merged