Update metadata script example, update nc2mmd usage example
metno/data-management-handbook pull request #98
Opened 2023-04-28 12:26 UTC by charlienegri

2023-05-03 06:55 UTC, charlienegri commented
other places in this repo where we need to update?

2023-05-09 07:37 UTC, mortenwh requested changes
Looks good but I'm a bit unsure about the featureType, as mentioned in the comment

2023-05-09 07:37 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +
This is a gridded dataset, right? I don't think we should use the featureType in that case... Can you check with @magnarem ?

2023-05-09 07:37 UTC, mortenwh commented on example_scripts/update_meps_file.py
> +
See comment below

2023-05-09 09:59 UTC, magnarem commented on source/add_metadata_python_script_example.adoc
> +
It will be up to the data-producers to determine if the dataset should have a feature_type or not. 
So if the dataset have a data-structure that conforms to one of the feature types  in https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_features_and_feature_types, then they add this attribute, if not, it is not needed. So we only extract feature_type if it exists and have the right vocabulary (name).

2023-05-10 08:22 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +
if I do not add it I get a warning like this 
```
/home/charlien/v/senda/lib/python3.10/site-packages/py_mmd_tools/nc_to_mmd.py:1344: UserWarning: 
	CF attribute featureType is missing - one of the feature types listed in Table 9.1 in https://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#_features_and_feature_types should be used.
  warnings.warn('\n\t'+'\n\t'.join(self.missing_attributes['warnings']))
```

2023-05-10 08:41 UTC, magnarem commented on source/add_metadata_python_script_example.adoc
> +
Yes. A warning is ok.

Maybe the warning should state, that this field is recommended to add if the dataset applies to the feature types listed in this table 9.1

2023-05-10 11:03 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +
The warning is coming from py-mmd-tools. It would be good to write a comment regarding the warning (that this field is recommended if the dataset applies to the feature types listed in table 9.1), and any other warnings that you might get. And then not to add the featureType for this dataset.

2023-05-10 13:02 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +
Maybe it is me who misunderstand but I wouldn't call a model forecast with time steps a time series. To my understanding, that would rather be a series of measurements in a longer time range (like from an in-situ measurement).

2023-05-10 13:04 UTC, johtoblan commented on source/add_metadata_python_script_example.adoc
> +
From the CF-standard document above

> Discrete sampling geometry datasets are characterized by a dimensionality that is lower than that of the space-time region that is sampled
The gridded data has the same (or higher) dimensionality  than the space-time region that is sampled

2023-05-10 13:05 UTC, johtoblan commented on source/add_metadata_python_script_example.adoc
> +
and how one define sampling is also critical I guess, but weird that FEATURE = grid does not exist

2023-05-10 13:12 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
> +
:+1: noted

2023-05-16 13:26 UTC, mortenwh requested changes
I'm adding the suggested changes but can you reduce the size of nc-file?

2023-05-16 13:26 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
> +$ ./nc2mmd.py -u https://thredds.met.no/thredds/dodsC/metusers/magnusu/test-2023-02-03/meps_reduced.nc -i <path-to-data-management-handbook>/example_scripts/meps_reduced.nc -o .
```suggestion
$ nc2mmd -u https://thredds.met.no/thredds/dodsC/metusers/magnusu/test-2023-02-03/meps_reduced.nc -i <path-to-data-management-handbook>/example_scripts/meps_reduced.nc -o .
```

2023-05-16 13:26 UTC, mortenwh commented on source/register_context.adoc
> +./nc2mmd.py -u <OPeNDAP url of your netcdf file> -i <path to your netcdf file> -o <your xml output directory>
```suggestion
nc2mmd -u <OPeNDAP url of your netcdf file> -i <path to your netcdf file> -o <your xml output directory>
```

2023-05-16 13:41 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
>  $ wget https://thredds.met.no/thredds/fileServer/metusers/magnusu/test-2023-02-03/meps_reduced.nc
it is just one variable from a regular meps file 
(see the history field in the metadata for how it was created 
```:history = "Fri Feb  3 12:21:40 2023: ncks -v x_wind_10m --deflate 3 /lustre/storeB/project/metproduction/products/meps/meps_lagged_6_h_latest_2_5km_20230201T09Z.nc meps_reduced.nc\n2023-02-01T11:30:05 creation by fimex" ;```
)
I am not sure I see a way to make it smaller that makes sense, we can change the example entirely of course and pick something else (but then we need to re-write the description in the .adoc file here)

2023-05-16 14:00 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
>  $ wget https://thredds.met.no/thredds/fileServer/metusers/magnusu/test-2023-02-03/meps_reduced.nc
ok - we can also reduce it later if necessary. Maybe add a comment "Go for a coffee" or something :-P

2023-05-16 14:01 UTC, mortenwh commented on source/add_metadata_python_script_example.adoc
>  $ wget https://thredds.met.no/thredds/fileServer/metusers/magnusu/test-2023-02-03/meps_reduced.nc
Anyway - if my changes look ok, I suggest that you merge this. Can you take a look at my PR in py-mmd-tools? This is needed for the example to work.

2023-05-16 15:09 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
>  $ wget https://thredds.met.no/thredds/fileServer/metusers/magnusu/test-2023-02-03/meps_reduced.nc
the PR looks ok,  
I was thinking that for consistency with `./nc2mmd.py --help` at line 31 maybe we shoud use the exact same at line 28  
I wrote `nc2mmd` as the command/endpoint that becomes available in the env where py-mmd-tools is installed, and you don't need to be in the script folder to use it, but if we want consistency with the rest we should keep `./nc2mmd.py` perhaps  
on the size, perhaps we could write the size explicitly so that ppl know what to expect...

2023-05-16 15:26 UTC, charlienegri commented on source/add_metadata_python_script_example.adoc
>  $ wget https://thredds.met.no/thredds/fileServer/metusers/magnusu/test-2023-02-03/meps_reduced.nc
I will push these small edits asap

2023-05-16 15:48 UTC, charlienegri commented
added warning about the size and went for using the endpoint `nc2mmd` everywhere instead of the `.py`

2023-05-16 20:03 UTC, merged